trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '62f9f89c-9f06-4957-9e86-f06b3b597259'

- task: SonarCloudPrepare@1
  displayName: 'Prepare Sonar Cloud Analysis'
  inputs:
    SonarCloud: 'AzureDevops'
    organization: 'vignesh19930919'
    scannerMode: 'MSBuild'
    projectKey: 'Vignesh19930919_BlazorApp'
    projectName: 'AzureDevops'
    projectVersion: '$(Build.BuildNumber)'
    extraProperties: |
      sonar.cs.opencover.reportspaths=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.opencover.xml
      sonar.exclusions=**/wwwroot/lib/**/*
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack the Project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'

- task: NuGetCommand@2
  displayName: 'Push the NuGet Package'
  inputs:
    command: 'push'
    publishVstsFeed: '3582d680-170d-470f-aa86-3ebf88e62c14'
- task: CopyFiles@2
  inputs:
    Contents: '**/bin/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
